In [2]:
!pip install git+https://github.com/ryan112358/private-pgm.git

Collecting git+https://github.com/ryan112358/private-pgm.git
  Cloning https://github.com/ryan112358/private-pgm.git to /tmp/pip-req-build-oey8q2qi
  Running command git clone --filter=blob:none --quiet https://github.com/ryan112358/private-pgm.git /tmp/pip-req-build-oey8q2qi
  Resolved https://github.com/ryan112358/private-pgm.git to commit 4152cc591f30560ce994870318ee4801b016bf94
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (1.13.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (2.1.4)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (3.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (3.7.1)
Requirement already satisfied: nose in /usr/local/lib/python3.10/dist-packages (from private-pgm==0.0.1) (1.3.7)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->private-pgm==0.0.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->private-pgm==0.0.1) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->private-pgm==0.0.1) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->private-pgm==0.0.1) (1.16.0)

In [3]:
!pip install disjoint-set

Requirement already satisfied: disjoint-set in /usr/local/lib/python3.10/dist-packages (0.8.0)

In [4]:
!pip install smartnoise-synth

Requirement already satisfied: smartnoise-synth in /usr/local/lib/python3.10/dist-packages (1.0.4)
Requirement already satisfied: Faker>=17.0.0 in /usr/local/lib/python3.10/dist-packages (from smartnoise-synth) (28.1.0)
Requirement already satisfied: opacus<0.15.0,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from smartnoise-synth) (0.14.0)
Requirement already satisfied: pac-synth<0.0.9,>=0.0.8 in /usr/local/lib/python3.10/dist-packages (from smartnoise-synth) (0.0.8)
Requirement already satisfied: smartnoise-sql<2.0.0,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from smartnoise-synth) (1.0.4)
Requirement already satisfied: torch>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from smartnoise-synth) (2.4.0+cu121)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker>=17.0.0->smartnoise-synth) (2.8.2)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.10/dist-packages (from opacus<0.15.0,>=0.14.0->smartnoise-synth) (1.26.4)
Requirement already satisfied: scipy>=1.2 in /usr/local/lib/python3.10/dist-packages (from opacus<0.15.0,>=0.14.0->smartnoise-synth) (1.13.1)
Requirement already satisfied: PyYAML<7.0.0,>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (6.0.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.3 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (4.9.3)
Requirement already satisfied: graphviz<0.18,>=0.17 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (0.17)
Requirement already satisfied: opendp<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (0.10.0)
Requirement already satisfied: pandas<3.0.0,>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (2.1.4)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (2.0.32)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (1.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2.2.0->smartnoise-synth) (2024.6.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.1->smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0.0,>=2.0.1->smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker>=17.0.0->smartnoise-synth) (1.16.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<3.0.0,>=2.0.0->smartnoise-sql<2.0.0,>=1.0.4->smartnoise-synth) (3.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.2.0->smartnoise-synth) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.2.0->smartnoise-synth) (1.3.0)

In [5]:
!pip install sdv

Requirement already satisfied: sdv in /usr/local/lib/python3.10/dist-packages (1.16.1)
Requirement already satisfied: boto3<2.0.0,>=1.28 in /usr/local/lib/python3.10/dist-packages (from sdv) (1.35.10)
Requirement already satisfied: botocore<2.0.0,>=1.31 in /usr/local/lib/python3.10/dist-packages (from sdv) (1.35.10)
Requirement already satisfied: cloudpickle>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (2.2.1)
Requirement already satisfied: graphviz>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.17)
Requirement already satisfied: tqdm>=4.29 in /usr/local/lib/python3.10/dist-packages (from sdv) (4.66.5)
Requirement already satisfied: copulas>=0.11.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.11.1)
Requirement already satisfied: ctgan>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.10.1)
Requirement already satisfied: deepecho>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.6.0)
Requirement already satisfied: rdt>=1.12.3 in /usr/local/lib/python3.10/dist-packages (from sdv) (1.12.3)
Requirement already satisfied: sdmetrics>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (0.15.1)
Requirement already satisfied: platformdirs>=4.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (4.2.2)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.10/dist-packages (from sdv) (6.0.2)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from sdv) (2.1.4)
Requirement already satisfied: numpy<2.0.0,>=1.23.3 in /usr/local/lib/python3.10/dist-packages (from sdv) (1.26.4)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from boto3<2.0.0,>=1.28->sdv) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from boto3<2.0.0,>=1.28->sdv) (0.10.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/dist-packages (from botocore<2.0.0,>=1.31->sdv) (2.0.7)
Requirement already satisfied: plotly>=5.10.0 in /usr/local/lib/python3.10/dist-packages (from copulas>=0.11.0->sdv) (5.24.0)
Requirement already satisfied: scipy>=1.9.2 in /usr/local/lib/python3.10/dist-packages (from copulas>=0.11.0->sdv) (1.13.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from ctgan>=0.10.0->sdv) (2.4.0+cu121)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->sdv) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->sdv) (2024.1)
Requirement already satisfied: Faker>=17 in /usr/local/lib/python3.10/dist-packages (from rdt>=1.12.3->sdv) (28.1.0)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from rdt>=1.12.3->sdv) (1.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.10.0->copulas>=0.11.0->sdv) (9.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=5.10.0->copulas>=0.11.0->sdv) (24.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.31->sdv) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.12.3->sdv) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.1.0->rdt>=1.12.3->sdv) (3.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (1.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.11.0->ctgan>=0.10.0->sdv) (2024.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.11.0->ctgan>=0.10.0->sdv) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.11.0->ctgan>=0.10.0->sdv) (1.3.0)

In [6]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd
import re
import numpy as np
from snsynth import Synthesizer
from snsynth.mst import MSTSynthesizer
import json

Mounted at /content/drive

In [7]:
import sdv

In [8]:
# Metadata

constant_head = ["relationship_to_head", "sex", "race", "hispanicity",
            "sample_or_nonsample", "person_number", "both_parents_grewup",
            "area_size_grewup", "state_grewup", "region_grewup"]

constant_indiv_75_90 = ["sex", "lnps_eligible", "lnps_residence",
            "sample_or_nonsample", "person_number"]

constant_indiv_05_21 = ["sex", "lnps_eligible", "lnps_residence",
            "sample_or_nonsample", "person_number"]


paths =  {"head":
            {"data": "drive/MyDrive/Knexus/psid/data/head_87_96/psid_head_87_96_wide.csv",
             "dict": "drive/MyDrive/Knexus/psid/data/head_87_96/data_dictionary.json",
             "constant": constant_head},
          "indiv_75_90":
            {"data": "drive/MyDrive/Knexus/psid/data/indiv_75_90/psid_indiv_75_90_wide.csv",
             "dict": "drive/MyDrive/Knexus/psid/data/indiv_75_90/data_dict_indiv.json",
             "constant": constant_indiv_75_90},
          "indiv_05_21":
            {"data": "drive/MyDrive/Knexus/psid/data/indiv_05_21/psid_indiv_05_21_wide.csv",
             "dict": "drive/MyDrive/Knexus/psid/data/indiv_05_21/data_dict_indiv_health.json",
             "constant": constant_indiv_05_21}
          }

In [9]:
df_head = pd.read_csv(paths['head']['data'])
df_indiv_75_90 = pd.read_csv(paths['indiv_75_90']['data'])
df_indiv_05_21 = pd.read_csv(paths['indiv_05_21']['data'])

In [10]:
df_head

,ID_indiv,relationship_to_head,sex,race,hispanicity,region_grewup,state_grewup,area_size_grewup,both_parents_grewup,age_87,...,vacation_last_year_89,vacation_last_year_90,vacation_last_year_91,vacation_last_year_92,vacation_last_year_93,vacation_last_year_94,vacation_last_year_95,vacation_last_year_96,person_number,sample_or_nonsample
0,4001,1,1,1,0,3,41,1,1,64,...,1,2,2,2,2,0,0,0,1,1
1,4003,1,1,1,0,3,41,1,1,35,...,2,2,2,2,0,2,1,1,1,1
2,4172,1,1,1,0,3,41,1,1,38,...,1,1,1,1,1,1,1,1,5,3
3,5001,1,1,1,0,3,41,1,1,43,...,2,2,2,0,2,2,1,1,1,1
4,5003,1,1,1,0,3,41,2,1,24,...,2,2,0,0,2,2,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4039,6867015,1,1,2,0,3,42,3,2,20,...,1,1,2,0,2,2,1,1,1,1
4040,6868001,1,2,2,0,3,42,2,1,69,...,0,0,0,0,0,0,0,0,1,1
4041,6868170,1,1,2,0,3,42,2,2,40,...,1,1,1,1,1,1,1,1,5,3
4042,6872001,1,2,2,0,3,3,2,1,51,...,0,2,2,0,0,0,0,0,1,1
4043,6872003,1,1,2,0,2,12,3,2,25,...,2,1,1,1,1,1,2,1,1,1

In [10]:
# Methods:
# Non-AI Models:
# --rsynthpop CART
# --smartnoise AIM (may not be able to get it to run)
# --smartnoise MST
# --** Synthetic Data Vault fast_ml (this should run, gaussican copula)
# --Do the SmartNoise people have any recommendations?
# AI - Models:
# --Synthetic Data Vault TVAE
# --Smartnoise PATE CTGAN
# --** GretelAI (what options do they have?)
# Simple Methods:
# --** uniform random 40% subsample

# rsynthpop CART

In [11]:
# df

In [12]:
# cf R

# smartnoise AIM

In [ ]:
synth = Synthesizer.create("aim", epsilon=3.0, verbose=True)
synth.fit(df, preprocessor_eps=1.0)
pums_synth = synth.sample(1000)

Spent 0.9999999999999998 epsilon on preprocessor, leaving 2.0 for training
Fitting with 0 dimensions
361

KeyboardInterrupt:

# smartnoise MST

In [ ]:
synth = Synthesizer.create("mst", epsilon=3.0, verbose=True)
synth.fit(df, preprocessor_eps=1.0)
pums_synth = synth.sample(1000)

Spent 0.9999999999999998 epsilon on preprocessor, leaving 2.0 for training
Fitting with 0 dimensions
Getting cliques

# fast_ml

In [ ]:
# deprecated

# gaussican copula

Our data dictionary (first_dict) may be inconsistent with the metadata dictionary inferred by the sdv method (second_dict).

sdv metadata is \\
{columns: {  age_87: {sdtype: numerical}  }, {  age_88: {sdtype: numerical}  } ... }

feature_type_dict is \\
{categorical: list, ordinal: list, continuous: list}

To compare them, for each, I create a dictionary of the form {feature name: type, ...}, and print feature name when the types do not coincide, I replace continuous by numerical in the first_dict

In [11]:
from sdv.metadata import SingleTableMetadata
import json

In [13]:
!pip install ijson

Collecting ijson
  Downloading ijson-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Downloading ijson-3.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 4.7 MB/s eta 0:00:00
Installing collected packages: ijson
Successfully installed ijson-3.3.0

In [41]:
import ijson

def my_dict(name):
    # Path to the JSON file (assuming it's in the same folder as your script)
    json_file_path = paths[name]["dict"]

    # Create the dictionary with keys 'categorical', 'ordinal', and 'continuous'
    feature_type_dict = {
        "categorical": [],
        "ordinal": [],
        "continuous": []
    }

    # Stream through the JSON data incrementally
    with open(json_file_path, 'r') as file:
        parser = ijson.items(file, '')

        # Extract the first object, which contains the JSON key-value pairs
        json_data = next(parser)

    # Parse through the JSON structure and assign column names to the corresponding feature types
    for column, attributes in json_data.items():
        feature_type = attributes.get("feature type")

        if feature_type in feature_type_dict:
            feature_type_dict[feature_type].append(column)
        else:
            print(f"Unknown feature type for column '{column}': {feature_type}")

    # remove year, and merge ordinal and categorical as ordinal is not a recognized type by sdv synthesizers
    feature_type_dict["ordinal"].remove("year")
    feature_type_dict['categorical'].extend(feature_type_dict['ordinal'])
    del feature_type_dict['ordinal']

    # PB: the feature_type dictionary does not contain the "_year" features at this point

    # Process each feature type
    for data_type in feature_type_dict:
        updated_features = []

        for feature in feature_type_dict[data_type]:
            if feature in paths[name]["constant"]:
                updated_features.append(feature)
            else:
                updated_features.extend([f"{feature}_{i}" for i in range(87, 97)])

        # Replace the old list with the updated one
        feature_type_dict[data_type] = updated_features

    return feature_type_dict

In [42]:
# def my_dict(name):

#     # Path to the JSON file (assuming it's in the same folder as your script)
#     json_file_path = paths[name]["dict"]

#     # Load the JSON data from the file
#     with open(json_file_path, 'r') as file:
#         json_data = json.load(file)

#     # Create the dictionary with keys 'categorical', 'ordinal', and 'continuous'
#     feature_type_dict = {
#         "categorical": [],
#         "ordinal": [],
#         "continuous": []
#     }

#     # Parse through the JSON structure and assign column names to the corresponding feature types
#     for column, attributes in json_data.items():
#         feature_type = attributes.get("feature type")

#         if feature_type == "categorical":
#             feature_type_dict["categorical"].append(column)
#         elif feature_type == "ordinal":
#             feature_type_dict["ordinal"].append(column)
#         elif feature_type == "continuous":
#             feature_type_dict["continuous"].append(column)
#         else:
#             print(f"Unknown feature type for column '{column}': {feature_type}")

#         # PB: the feature_type dictionary does not contain the "_year" features at this point

#         for data_type in feature_type_dict.keys():
#             # For each data_type: categorical, continuous, ordinal
#             new_features = []
#             for feature in feature_type_dict[data_type]:
#                 # For each feature, add feature_87, feature_88, ..., feature_96, except if feature is constant
#                 if feature in paths[name]["constant"]:
#                     new_features.append(feature)
#                 else:
#                     new_features.extend([f"{feature}_{i}" for i in range(87, 97)])

#             # New_features is now the updated list of features for the current data_type
#             feature_type_dict[data_type] = new_features

#     return feature_type_dict

In [43]:
def preproc_my_dict(first_dict):
    new_first_dict = {
      "numerical" if key == "continuous" else key: value
      for key, value in first_dict.items()
      }

    # Reverse first_dict to map feature names to types
    reversed_first_dict = {}
    for key, values in new_first_dict.items():
        for value in values:
            reversed_first_dict[value] = key

    return reversed_first_dict

In [54]:
# Function to find and print discrepancies
def check_discrepancies(reversed_first_dict, second_dict):
    '''
    reversed_first_dict: my reversed dictionary {feature name: type}
    second_dict: sdv metadata dictionary
    '''
    print("Checking for discrepancies...")

    columns_with_specific_types = {}

    columns_with_wrong_types = []

    # Iterate through the second_dict and compare
    for col_name, col_info in second_dict["columns"].items():
        # col_name is the feature name, col_info is a dictionary e.g. {'sdtype': "numerical"}
        second_type = col_info["sdtype"]
        first_type = reversed_first_dict.get(col_name)

        if second_type not in ["categorical", "numerical"]:
            columns_with_specific_types[col_name] = second_type
        else:
            # second_type is either categorical or numerical but differs from reversed_first_dict
            # enforce the reversed_first_dict type
            if first_type != second_type:
                columns_with_wrong_types.append(col_name)

    print(f"Columns with specific types:{columns_with_specific_types}")
    print(f"Fail if > 0: Number of columns with wrong types: {len(columns_with_wrong_types)}")
    print("Done")
    return columns_with_wrong_types, columns_with_specific_types

In [55]:
from sdv.single_table import GaussianCopulaSynthesizer

def gaussian_copula(name):
    df = pd.read_csv(paths[name]['data'])

    metadata = SingleTableMetadata()
    metadata.detect_from_dataframe(df)

    feature_type_dict = my_dict(name)
    reversed_first_dict = preproc_my_dict(feature_type_dict)

    # Check discrepancies and return list of columns where the reversed_first_dict type needs to be enforced
    # i.e. wrong type is inferred by sdv metadata
    print("First check")
    columns_with_wrong_types, _ = check_discrepancies(reversed_first_dict, metadata.to_dict())
    for col in columns_with_wrong_types:
        metadata.update_column(
            column_name=col,
            sdtype=reversed_first_dict[col]
        )
    print("Second check after update")
    _, __ = check_discrepancies(reversed_first_dict, metadata.to_dict())

    metadata.validate()
    synthesizer = GaussianCopulaSynthesizer(metadata)
    synthesizer.fit(df)

    synthetic_data = synthesizer.sample(num_rows=df.shape[0])

    return synthetic_data

In [56]:
synthetic_data = gaussian_copula("head")

Unknown feature type for column 'ID_indiv': id
First check
Checking for discrepancies...
Columns with specific types:{'ID_indiv': 'id', 'state_grewup': 'administrative_unit', 'state_current_87': 'administrative_unit', 'state_current_88': 'administrative_unit', 'state_current_89': 'administrative_unit', 'state_current_90': 'administrative_unit', 'state_current_91': 'administrative_unit', 'state_current_92': 'administrative_unit', 'state_current_93': 'administrative_unit', 'state_current_94': 'administrative_unit', 'state_current_95': 'administrative_unit', 'state_current_96': 'administrative_unit'}
Fail if > 0: Number of columns with wrong types: 138
Done
Second check after update
Checking for discrepancies...
Columns with specific types:{'ID_indiv': 'id', 'state_grewup': 'administrative_unit', 'state_current_87': 'administrative_unit', 'state_current_88': 'administrative_unit', 'state_current_89': 'administrative_unit', 'state_current_90': 'administrative_unit', 'state_current_91': 'administrative_unit', 'state_current_92': 'administrative_unit', 'state_current_93': 'administrative_unit', 'state_current_94': 'administrative_unit', 'state_current_95': 'administrative_unit', 'state_current_96': 'administrative_unit'}
Fail if > 0: Number of columns with wrong types: 0
Done

/usr/local/lib/python3.10/dist-packages/sdv/single_table/base.py:97: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

In [57]:
synthetic_data

,ID_indiv,relationship_to_head,sex,race,hispanicity,region_grewup,state_grewup,area_size_grewup,both_parents_grewup,age_87,...,vacation_last_year_89,vacation_last_year_90,vacation_last_year_91,vacation_last_year_92,vacation_last_year_93,vacation_last_year_94,vacation_last_year_95,vacation_last_year_96,person_number,sample_or_nonsample
0,937873886,1,1,1,0,2,North Carolina,3,2,30,...,1,1,1,1,1,1,2,1,1,1
1,420136679,1,2,1,0,4,Indiana,3,1,57,...,1,2,1,1,0,0,1,1,1,1
2,17938750,1,1,1,0,2,Maine,3,1,40,...,1,1,1,2,1,1,2,1,1,1
3,98569090,1,2,2,0,3,Oklahoma,3,1,42,...,1,2,1,1,0,1,1,1,5,1
4,723351393,1,2,1,0,4,Idaho,3,1,36,...,0,0,1,0,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4039,966670958,1,1,2,0,3,Oklahoma,3,1,19,...,1,2,1,2,0,0,1,1,5,1
4040,132161144,1,1,1,0,3,Texas,2,1,34,...,1,1,0,1,1,1,1,1,1,1
4041,942306856,1,2,2,0,1,Utah,2,1,50,...,1,1,2,1,1,0,1,1,1,1
4042,305103319,1,1,2,0,3,Washington,2,2,46,...,1,0,0,0,1,0,1,1,1,1
4043,518601630,1,1,1,0,2,Kentucky,3,1,25,...,0,0,0,0,1,1,1,1,1,3

In [58]:
# https://psidonline.isr.umich.edu/data/Documentation/PSIDStateCodes.pdf
# Dictionary to map state names to state numbers based on the provided data
state_to_number = {
    "Alabama": 1,
    "Arizona": 2,
    "Arkansas": 3,
    "California": 4,
    "Colorado": 5,
    "Connecticut": 6,
    "Delaware": 7,
    "District of Columbia": 8,
    "Florida": 9,
    "Georgia": 10,
    "Idaho": 11,
    "Illinois": 12,
    "Indiana": 13,
    "Iowa": 14,
    "Kansas": 15,
    "Kentucky": 16,
    "Louisiana": 17,
    "Maine": 18,
    "Maryland": 19,
    "Massachusetts": 20,
    "Michigan": 21,
    "Minnesota": 22,
    "Mississippi": 23,
    "Missouri": 24,
    "Montana": 25,
    "Nebraska": 26,
    "Nevada": 27,
    "New Hampshire": 28,
    "New Jersey": 29,
    "New Mexico": 30,
    "New York": 31,
    "North Carolina": 32,
    "North Dakota": 33,
    "Ohio": 34,
    "Oklahoma": 35,
    "Oregon": 36,
    "Pennsylvania": 37,
    "Rhode Island": 38,
    "South Carolina": 39,
    "South Dakota": 40,
    "Tennessee": 41,
    "Texas": 42,
    "Utah": 43,
    "Vermont": 44,
    "Virginia": 45,
    "Washington": 46,
    "West Virginia": 47,
    "Wisconsin": 48,
    "Wyoming": 49,
    "Alaska": 50,
    "Hawaii": 51
}

# # Update the "state" column by mapping state names to state numbers
# synthetic_data['state'] = synthetic_data['state'].map(state_to_number)

columns_to_map = ['state_grewup'] + [f"state_current_{x}" for x in range(87,97)]

In [59]:
for c in columns_to_map:
    synthetic_data[c] = synthetic_data[c].map(state_to_number)

In [ ]:
synthetic_data.to_csv("drive/MyDrive/Knexus/psid/head_87_96/psid_head_87_96_gaussian_copula_wide_august30.csv", index=False)

# TVAE

In [ ]:
from sdv.single_table import TVAESynthesizer

synthesizer = TVAESynthesizer(metadata)
synthesizer.fit(df)

synthetic_data = synthesizer.sample(num_rows=df.shape[0])

/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()

# smartnoise PATE CTGAN

In [ ]:
import pandas as pd
from snsynth import Synthesizer

synth = Synthesizer.create("patectgan", epsilon=1.0, verbose=True)
synth.fit(df, preprocessor_eps=0.3)

Spent 0.9999999999999998 epsilon on preprocessor, leaving 2.0 for training
using loss cross_entropy and regularization None
eps: 0.125422 	 G: 2.932676 	 D: 1.049780
eps: 0.505844 	 G: 4.884159 	 D: 1.993661
eps: 0.718349 	 G: 3.954535 	 D: 1.802874
eps: 0.882490 	 G: 4.840546 	 D: 2.033623
eps: 1.021688 	 G: 4.897354 	 D: 2.065470
eps: 1.145101 	 G: 4.455063 	 D: 2.204450
eps: 1.257111 	 G: 5.329026 	 D: 2.393914
eps: 1.360116 	 G: 4.622821 	 D: 2.330400
eps: 1.456790 	 G: 4.409969 	 D: 2.296293
eps: 1.547777 	 G: 5.366455 	 D: 2.798537
eps: 1.633888 	 G: 5.504626 	 D: 2.442281
eps: 1.716147 	 G: 5.118363 	 D: 2.311059
eps: 1.795872 	 G: 5.403521 	 D: 2.914433
eps: 1.870872 	 G: 4.956523 	 D: 2.789606
eps: 1.944786 	 G: 4.542884 	 D: 2.709465

In [ ]:
deid_df = synth.sample(df.shape[0])

In [ ]:
deid_df

,ID_indiv,relationship_to_head_87,relationship_to_head_88,relationship_to_head_89,relationship_to_head_90,relationship_to_head_91,relationship_to_head_92,relationship_to_head_93,relationship_to_head_94,relationship_to_head_95,...,sample_or_nonsample_87,sample_or_nonsample_88,sample_or_nonsample_89,sample_or_nonsample_90,sample_or_nonsample_91,sample_or_nonsample_92,sample_or_nonsample_93,sample_or_nonsample_94,sample_or_nonsample_95,sample_or_nonsample_96
0,5.152815e+06,1,1,1,1,1,1,1,1,1,...,1,2,1,1,1,1,2,1,1,1
1,5.913035e+06,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,4.399346e+06,1,1,1,1,1,1,1,1,1,...,3,1,1,1,4,2,1,1,0,4
3,5.314245e+06,1,1,1,1,1,1,1,1,1,...,0,2,1,1,3,0,4,1,1,1
4,4.699756e+06,1,1,1,1,1,1,1,1,1,...,3,4,3,3,4,0,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4274,4.393464e+06,1,1,1,1,1,1,1,1,1,...,2,3,3,1,2,4,1,0,1,1
4275,4.475669e+06,1,1,1,1,1,1,1,1,1,...,1,3,1,3,1,2,1,0,3,1
4276,4.499491e+06,1,1,1,1,1,1,1,1,1,...,3,1,1,2,0,1,3,1,2,1
4277,5.522865e+06,1,1,1,1,1,1,1,1,1,...,0,4,0,3,3,1,1,1,1,3
4278,4.831453e+06,1,1,1,1,1,1,1,1,1,...,1,1,1,2,1,4,1,1,1,1

# GretelAI

In [ ]:
!pip install tensorflow==2.11 # for LSTM
!pip install sdv<0.18 # for ACTGAN
!pip install torch==2.0 # for Timeseries DGAN

In [ ]:
!pip install gretel-synthetics

# uniform random 40% subsample

In [ ]:
sampled_ids = df['ID_indiv'].drop_duplicates()
sampled_ids = sampled_ids.sample(frac=0.4, random_state=42)

sub_df = df[df['ID_indiv'].isin(sampled_ids)]

# MWEM

In [ ]:
synth = Synthesizer.create("mwem", epsilon=3.0, verbose=True)
synth.fit(df, preprocessor_eps=1.0)
deid_df2 = synth.sample(df.shape[0])

In [ ]:
# Domains = {col: df[col].nunique() for col in df.columns}
# # Convert dictionary to JSON formatted string
# json_str = json.dumps(Domains, indent=4)

# print(json_str)

In [ ]:
# Domains = {
#     "psid": "drive/MyDrive/Knexus/mst_dict.json"
# }

# mst_synth = MSTSynthesizer(domains_dict=Domains, domain='psid', epsilon=1.0)
# mst_synth.fit(df)
# sample_size = len(df)
# synth_data = mst_synth.sample(sample_size)

# categorical_columns=[s + f"_{i}" for s in feature_type_dict["categorical"] for i in range(87, 97)]
# ordinal_columns=[s + f"_{i}" for s in feature_type_dict["ordinal"] for i in range(87, 97)]
# continuous_columns=[s + f"_{i}" for s in feature_type_dict["continuous"] for i in range(87, 97)]

# df.drop(columns=["ID_indiv"], inplace=True)

# synth = Synthesizer.create("mst", epsilon=1.0)
# synth.fit(df,
#           categorical_columns=categorical_columns,
#           ordinal_columns=ordinal_columns,
#           continuous_columns=continuous_columns,
#           preprocessor_eps=0.3)

# syn_data = synth.sample(df.shape[0])
# syn_data.to_csv("drive/MyDrive/Knexus/head_mst_eps_1.csv", index=False)


# df.drop(columns=["ID_indiv"], inplace=True)

synth = Synthesizer.create("mst", epsilon=1.0)
synth.fit(df, preprocessor_eps=0.3)
syn_data = synth.sample(df.shape[0])
syn_data.to_csv("drive/MyDrive/Knexus/head_mst_eps_1.csv", index=False)

# continuous = ['age', 'income_labor_tot', 'income_needs_standard_orshansky', 'income_needs_standard_census']
# continuous = [s + f"_{i}" for s in continuous for i in range(87, 97)]

# categorical_columns = list(set(df.columns) - set(continuous))
# synth = Synthesizer.create('mst', epsilon=1.0)
# sample = synth.fit_sample(
#   df,
#   categorical_columns=categorical_columns,
#   continuous_columns=continuous,
#   preprocessor_eps=0.3,
#   nullable=True
# )
# print(sample)

ValueError: BinTransformer could not find bounds.